### ISSUE TITLE
Case (in)sensitivity? (Desktop.ini can be desktop.ini)

### ISSUE THREAD

**Issue by dprothero** [sindresorhus/junk#19]
On Windows, I noticed I had `desktop.ini` and it wasn't getting filtered out because the code looks for `Desktop.ini`. I could propose a PR to make the pattern `^[Dd]esktop.ini$`, but I wonder if it should just universally ignore case?

**Comment by sindresorhus** [comment]
> I could propose a PR to make the pattern ^[Dd]esktop.ini$, but I wonder if it should just universally ignore case?

I think it's best to simply handle this specific case. Making it ignore case for everything could have other side-effects.
