### ISSUE TITLE
Can not filter out following junk file

### ISSUE THREAD

**Issue by stone12379** [sindresorhus/junk#5]
/.Spotlight-V100/Store-V2/C6DBF25D-81D4-4B57-907E-B4A555E72C90/0.directoryStoreFile

Regards!
Joe

**Comment by sindresorhus** [comment]
Can you run `$ tree` (`brew install tree` if you don't already have it) inside your `.Spotlight-V100` directory?`

**Comment by stone12379** [comment]
Unfortunately, I can not reproduce this error after making some changes in my disk. However I would suggest to change '.../.Spotlight-V100$...' to '.../.Spotlight-V100[$/\]...' to prevent the problem to happen again.
